version: "3"
services:
  website:
    image:  nginx
    ports:
      - "8081:80"
    restart: always
  website2:
    image:  nginx
    ports:
      - "8082:80"
    restart: always
    networks:
      ttsdemo:
        ipv4_address:  192.168.99.10
networks:
  ttsdemo:
    ipam:
      driver:  default
      config:
        -  subnet:  "192.168.99.0/24"